version: '2'
services:
    # The Application
    app:
        build: ./php
        working_dir: /var/www
        volumes:
            - ./gaga-site-version-1:/var/www
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
    # The Web Server
    web:
        build: ./ngix
        working_dir: /var/www
        volumes_from:
            - app
        ports:
            - 8080:80
    # The Database
    database:
        image: mysql:5.6
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=homestead"
            - "MYSQL_USER=homestead"
        ports:
            - "33061:3306"
volumes:
    dbdata:
